all_atoms: true
atom_max_neighbors: 8
atom_radius: 5.0
batch_size: 8
c_alpha_max_neighbors: 24
cache_path: data/cache
config: null
cross_distance_embed_dim: 64
cross_max_distance: 20.0
cudnn_benchmark: true
data_dir: data/PDBBind_processed/
distance_embed_dim: 64
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: null
inference_earlystop_goal: min
inference_earlystop_metric: valinf_rmsd
inference_steps: 20
limit_complexes: 0
log_dir: workdir
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 300
no_batch_norm: false
no_torsion: true
ns: 48
num_conformers: 1
num_conv_layers: 6
num_dataloader_workers: 36
num_inference_complexes: 100
num_workers: 36
nv: 10
pin_memory: false
project: ligand_based_protein_score_model_train
receptor_radius: 30.0
remove_hs: true
restart_dir: workdir/ligand_based_protein_score_model
restart_lr: null
run_name: ligand_based_protein_score_model
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
side_sigma_max: 3.14
side_sigma_min: 0.0314
sigma_embed_dim: 64
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
test_sigma_intervals: true
train_inference_freq: null
use_ema: true
use_second_order_repr: false
val_inference_freq: 5
w_decay: 0.0
wandb: false
